// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: image/image.proto

package image

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on PutRequest with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *PutRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Url

	return nil
}

// PutRequestValidationError is the validation error returned by
// PutRequest.Validate if the designated constraints aren't met.
type PutRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutRequestValidationError) ErrorName() string { return "PutRequestValidationError" }

// Error satisfies the builtin error interface
func (e PutRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutRequestValidationError{}

// Validate checks the field values on PutResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *PutResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for S3Url

	return nil
}

// PutResponseValidationError is the validation error returned by
// PutResponse.Validate if the designated constraints aren't met.
type PutResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PutResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PutResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PutResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PutResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PutResponseValidationError) ErrorName() string { return "PutResponseValidationError" }

// Error satisfies the builtin error interface
func (e PutResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPutResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PutResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PutResponseValidationError{}

// Validate checks the field values on RemoveRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *RemoveRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for S3Url

	return nil
}

// RemoveRequestValidationError is the validation error returned by
// RemoveRequest.Validate if the designated constraints aren't met.
type RemoveRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoveRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoveRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoveRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoveRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoveRequestValidationError) ErrorName() string { return "RemoveRequestValidationError" }

// Error satisfies the builtin error interface
func (e RemoveRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoveRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoveRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoveRequestValidationError{}
